#!/bin/bash
echo -e '\n-------------------------------------------'
# argument based project generate a line of random string which help combination of string
cat /dev/random | tr -dc '[(+.)A-Za-z0-9_!]' | fold -w 20 | head -n $1
echo -e '-------------------------------------------\n'
